### GET All Product
GET localhost:8081/api/product

### GET All Transaction
GET localhost:8081/api/transaction

### GET Transaction By ID
GET localhost:8081/api/transaction/f91b494d-d2fe-476b-8e18-0a62b9077374

### GET All Customer
GET localhost:8081/api/customer

### GET Customer By ID
GET localhost:8081/api/customer/ffb57840-7b66-4ec4-925b-27e4fdc3d0c6

### POST Customer
POST localhost:8081/api/customer
Content-Type: application/json

{
  "address": "Jalan",
  "name":"Ayu",
  "email": "ayu@gmail.com",
  "phoneNumber": "0872622"
}

### GET Customer
GET localhost:8081/api/customer?sort=-name

### GET Store
GET localhost:8081/api/store?q=Toko Jakut