### Login Customer
POST {{localhost}}/auth/login
Content-Type: application/json

{
  "username": "refanzzzz",
  "password": "123"
}

> {%
    client.global.set("access_token", response.body.data.accessToken);
%}

### Login Admin
POST {{localhost}}/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "123"
}

> {%
    client.global.set("access_token", response.body.data.accessToken);
%}

### Refresh Token
POST {{localhost}}/auth/refresh-token

### Logout
POST {{localhost}}/auth/logout
Authorization: Bearer {{access_token}}

