### GET All Customer
GET {{localhost}}/customer
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ0b2tvbnlhZGlhIiwiaWF0IjoxNzI4ODczMzUyLCJleHAiOjE3Mjg4NzM2NTIsInN1YiI6ImZkZGFmZGEyLTI1N2YtNDlhMC1hM2YxLTk0YWVjOGE3NTQ3NiIsInJvbGUiOiJBZG1pbiJ9.vZxYsKIJQdpQQsIEiURfR_p1rPLCJCAbYcYJaPkedpU

### GET Customer By ID
GET localhost:8081/api/customer/ffb57840-7b66-4ec4-925b-27e4fdc3d0c6

### POST Customer
POST localhost:8081/api/customer
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "address": "Jalan",
  "name":"Ayu",
  "email": "ayu@gmail.com",
  "phoneNumber": "0872622",
  "username": "ayuu",
  "password": "123"
}

### GET Customer
GET localhost:8081/api/customer?sort=-name