### GET All Product
GET localhost:8081/api/product

### GET Product
GET localhost:8081/api/product?sortBy=name

### GET Product By ID
GET {{localhost}}/product/hdhdhdhhdhd
Authorization: Bearer {{access_token}}


### POST Product
POST localhost:8081/api/product
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "name": "Oreno",
  "description": "Jajanan chiki bola bola dengan rasa keju",
  "price": 5000,
  "stock": 20,
  "storeId": "a49c5b1b-dc65-48f8-9225-afc436bd5f01"
}

### DELETE Product
DELETE localhost:8081/api/product/5ef4e978-a6ad-47c4-ab65-fc51f394bd69

### PUT Product
PUT {{localhost}}product/10bb30e8-d022-4f90-a62b-eead157cf4fa
Content-Type: application/json

{
  "name": "Marimbak Jambu Biji",
  "stock": 20,
  "price": 3000,
  "description": "Minuman serbuk rasa jambu biji",
  "storeId": "d709a133-87a8-4085-824c-3f8e3cf2005e"
}
