### CREATE Transaction
POST {{localhost}}/transaction
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "customerId": "aeb1417d-96b8-420b-98fe-6e4d63591ace"
}

### Add Item Transaction
POST {{localhost}}/transaction/7bba7c22-af8d-46ba-98b6-8405612d58dc/items
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "productId": "814da777-0306-4be4-9447-fdab86ef60d1",
  "qty": 10
}

